#Puerto del Socket
socket.puerto=6000

#Configuracion de SSQL Server
#db.url=jdbc:sqlserver://100.88.25.17,49172;database=CentralProveedor;encrypt=true;trustServerCertificate=true;
db.url=jdbc:sqlserver://localhost;instanceName=BIBILOTECABD;database=CentralProveedor;encrypt=true;trustServerCertificate=true;
db.usuario= charlie_dev
db.contrasena= charlie1234
