#Puerto del Socket
socket.puerto=6000

#Identificador Python para IDENTIFICADOR6
identificador.host=127.0.0.1
identificador.puerto=5000

#Cifrado AES compartido con C# y Python
aes.key=ClaveSecreta1234
aes.iv=VectorInicio1234

#Configuracion de SQL Server
db.url=jdbc:sqlserver://localhost:49172;databaseName=CentralProveedor;encrypt=true;trustServerCertificate=true;
db.usuario=charlie_dev
db.contrasena=Charlie1234
