# Configuración del Servidor Socket
socket.puerto=6000

# Configuración de SQL Server
db.url=jdbc:sqlserver://localhost:1433;databaseName=TuBaseDatos;encrypt=true;trustServerCertificate=true;
db.usuario= charlie1234
db.contrasena= TuPasswordSeguro123
